# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-31 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsilon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='avg_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='users',
            field=models.IntegerField(default=0),
        ),
    ]
